apiVersion: v1
kind: ConfigMap
metadata:
  name: execution-api-config
data:
  APP_ENV: "kubernetes-cloud"
  APP_VERSION: "0.3.0"
  DB_HOST: "execution-db.cj0mq8qu0pf6.eu-central-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "execution_db"
