apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: execution-api
  template:
    metadata:
      labels:
        app: execution-api
    spec:
      containers:
        - name: execution-api
          image: 704618571585.dkr.ecr.eu-central-1.amazonaws.com/execution-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: execution-api-config
                  key: APP_ENV
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: execution-api-config
                  key: APP_VERSION
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: execution-api-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: execution-api-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: execution-api-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: execution-api-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: execution-api-secrets
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20